/**
 * The curated factor library against the parser.
 *
 * The Alpha158 fixture next door is generated by qlib, so a typo there is a
 * qlib bug. These hundred-odd expressions are hand-written, which makes this the
 * test that stops a stray bracket in a YAML file reaching the canvas as a parse
 * error the user sees. They are also written in shapes qlib never emits: a
 * fractional window (Wilder smoothing is `EMA(x, 0.0714285714)`), a triple-
 * nested EMA, an `If` with an `And` condition, a five-hundred-character ADX.
 *
 * The fixture is generated by `python -m webapp.api.factorlab.export` and
 * committed, because vitest cannot import qlib. A backend test regenerates it in
 * memory and fails if the committed copy has rotted.
 */
import { describe, expect, it } from 'vitest'

import curated from '@/fixtures/curated.json'
import served from '@/fixtures/registry.json'
import { parse } from './parse'
import { FALLBACK_REGISTRY, mergeRegistry } from './registry'
import { serialize } from './serialize'
import type { ExprNode, OperatorRegistry } from './types'

const registry = mergeRegistry(served.operators as unknown as OperatorRegistry)

const FACTORS = curated.factors as {
  name: string; expression: string; family: string
  window: number | null; tags: string[]; fields: string[]; back_days: number | null
}[]

const read = (source: string, reg: OperatorRegistry = registry): ExprNode => {
  const result = parse(source, reg)
  if (!result.ok) throw new Error(`${source} — ${result.error.message}`)
  return result.node
}

/** Structural equality, ignoring the ids the parser mints fresh each time. */
function shape(node: ExprNode): unknown {
  if (node.kind === 'field') return { field: node.name }
  if (node.kind === 'const') return { const: node.value }
  return {
    op: node.op,
    args: Object.fromEntries(
      Object.entries(node.args).map(([k, v]) => [k, v ? shape(v) : null])),
    params: node.params,
  }
}

describe('the curated factor library', () => {
  it('is not empty', () => {
    expect(FACTORS.length).toBeGreaterThan(90)
  })

  it.each(FACTORS.map((f) => [f.name, f.expression]))(
    '%s parses with the served registry', (_name, expression) => {
      expect(() => read(expression)).not.toThrow()
    })

  it.each(FACTORS.map((f) => [f.name, f.expression]))(
    '%s parses with the built-in fallback registry too', (_name, expression) => {
      // The canvas falls back to FALLBACK_REGISTRY with the API down. A factor
      // that only parses against the served copy would be unusable offline.
      expect(() => read(expression, FALLBACK_REGISTRY)).not.toThrow()
    })

  it.each(FACTORS.map((f) => [f.name, f.expression]))(
    '%s survives parse -> render -> parse', (_name, expression) => {
      const once = read(expression)
      expect(shape(read(serialize(once, registry)))).toEqual(shape(once))
    })

  it.each(FACTORS.map((f) => [f.name, f.expression]))(
    '%s reaches a fixed point after one render', (_name, expression) => {
      const rendered = serialize(read(expression), registry)
      expect(serialize(read(rendered), registry)).toBe(rendered)
    })

  it('has unique names that are legal column identifiers', () => {
    const names = FACTORS.map((f) => f.name)
    expect(new Set(names).size).toBe(names.length)
    for (const name of names) {
      expect(name).toMatch(/^[A-Za-z_]\w*$/)
      expect(name.length).toBeLessThanOrEqual(40)
      expect(name.toUpperCase().startsWith('LABEL')).toBe(false)
    }
  })

  it('declares every family it uses', () => {
    const declared = new Set(curated.families.map((f) => f.key))
    for (const factor of FACTORS) expect(declared.has(factor.family)).toBe(true)
    for (const family of curated.families) {
      expect(FACTORS.filter((f) => f.family === family.key).length).toBe(family.count)
    }
  })

  it('reports a finite warm-up for every factor', () => {
    for (const factor of FACTORS) {
      expect(factor.back_days).not.toBeNull()
      expect(factor.back_days).toBeGreaterThanOrEqual(0)
    }
  })

  it('names only columns the stores actually carry', () => {
    const known = new Set(['open', 'high', 'low', 'close', 'volume', 'factor', 'change'])
    for (const factor of FACTORS) {
      for (const field of factor.fields) expect(known.has(field)).toBe(true)
    }
  })
})
