/**
 * The parser against the real thing: all 184 Alpha158 expressions, and the
 * served operator registry they are written in.
 *
 * These fixtures are generated by `python -m webapp.api.factorlab.export` and
 * committed, because vitest cannot import qlib. A backend test regenerates them
 * in memory and fails if the committed copy has rotted, so the pair is a pin
 * rather than a snapshot that quietly goes stale.
 *
 * This is a much harder test than the ten hand-copied catalog entries it joins.
 * Those were chosen; these are simply what qlib emits, including the shapes
 * nobody would think to write by hand -- nested Corr over Log over a division,
 * a Quantile with a float third argument, an If inside a Sum inside a Div.
 */
import { describe, expect, it } from 'vitest'

import library from '@/fixtures/library.json'
import served from '@/fixtures/registry.json'
import { parse } from './parse'
import { FALLBACK_REGISTRY, mergeRegistry, PRECEDENCE } from './registry'
import { serialize } from './serialize'
import type { ExprNode, OperatorRegistry } from './types'

const registry = mergeRegistry(served.operators as unknown as OperatorRegistry)

const INDICATORS = library.indicators as {
  name: string; expression: string; family: string; group: string
  window: number | null; fields: string[]; in_handler: boolean
}[]

function shape(node: ExprNode): unknown {
  if (node.kind === 'field') return { field: node.name }
  if (node.kind === 'const') return { const: node.value }
  return {
    op: node.op,
    args: Object.fromEntries(
      Object.entries(node.args).map(([k, v]) => [k, v ? shape(v) : null])),
    params: node.params,
  }
}

const read = (source: string, using: OperatorRegistry = registry): ExprNode => {
  const result = parse(source, using)
  if (!result.ok) throw new Error(`${source} -> ${result.error.message}`)
  return result.node
}

describe('the served registry', () => {
  it('offers 44 operators and refuses 6 with reasons', () => {
    expect(Object.keys(served.operators)).toHaveLength(44)
    expect(served.refused).toHaveLength(6)
    for (const entry of served.refused) {
      expect(entry.reason.length).toBeGreaterThan(40)
    }
  })

  it('includes the operators the parser tells people to write', () => {
    // The dead end this fixes: parse.ts answers `$a and $b` with "write
    // And(...)", and the built-in registry had no And to write.
    for (const name of ['And', 'Or', 'Not']) {
      expect(registry[name]).toBeDefined()
      expect(read(`${name}($close${name === 'Not' ? '' : ',$open'})`).kind).toBe('call')
    }
  })

  it('gives Kurt the minimum window qlib enforces, not the one it prints', () => {
    // qlib guards on `N < 4` and raises a message saying 5.
    expect(registry.Kurt.window?.min).toBe(4)
    expect(registry.Skew.window?.min).toBe(3)
  })

  it('does not give Ref the rolling semantics it does not have', () => {
    expect(registry.Ref.window?.expandingAtZero).toBe(false)
    expect(registry.Ref.window?.allowsNegative).toBe(true)
    expect(registry.Mean.window?.expandingAtZero).toBe(true)
    // Corr expands at zero but has no EWM branch.
    expect(registry.Corr.window?.expandingAtZero).toBe(true)
    expect(registry.Corr.window?.ewmBelowOne).toBe(false)
  })

  it('agrees with the built-in registry on every slot name', () => {
    // `mergeRegistry` swaps whole entries, and `call()` fills slots by name. A
    // served `feature_left` where the canvas expects `left` would build every
    // binary operator with two empty slots and no error anywhere.
    for (const [name, builtIn] of Object.entries(FALLBACK_REGISTRY)) {
      const entry = registry[name]
      if (!entry) continue
      expect(entry.slots.map((s) => s.name)).toEqual(builtIn.slots.map((s) => s.name))
      expect(entry.slots.map((s) => s.kind)).toEqual(builtIn.slots.map((s) => s.kind))
    }
  })

  it('agrees with the built-in registry on infix symbols and precedence', () => {
    // parse.ts reads precedence from its own BINARY table, not from the
    // registry, while serialize.ts reads it from here. Disagreement would break
    // the round trip silently rather than loudly.
    for (const [name, builtIn] of Object.entries(FALLBACK_REGISTRY)) {
      const entry = registry[name]
      if (!entry || !builtIn.symbol) continue
      expect(entry.symbol).toBe(builtIn.symbol)
      expect(entry.precedence).toBe(builtIn.precedence)
      expect(Boolean(entry.rightAssociative)).toBe(Boolean(builtIn.rightAssociative))
    }
    expect(registry.Power.precedence).toBe(PRECEDENCE.power)
  })
})

describe('the Alpha158 library', () => {
  it('is all 184, uniquely named', () => {
    expect(INDICATORS).toHaveLength(184)
    expect(new Set(INDICATORS.map((i) => i.name)).size).toBe(184)
  })

  it.each(INDICATORS.map((i) => [i.name, i.expression]))(
    '%s parses', (_name, expression) => {
      expect(() => read(expression)).not.toThrow()
    })

  it.each(INDICATORS.map((i) => [i.name, i.expression]))(
    '%s survives parse -> render -> parse', (_name, expression) => {
      const once = read(expression)
      const rendered = serialize(once, registry)
      expect(shape(read(rendered))).toEqual(shape(once))
    })

  it('reaches a byte-identical fixed point on the second render', () => {
    // Reformatting once is expected; reformatting forever would mean the
    // serialiser has no canonical form, and every save would churn the diff.
    for (const { name, expression } of INDICATORS) {
      const first = serialize(read(expression), registry)
      const second = serialize(read(first), registry)
      expect(second, name).toBe(first)
    }
  })

  it('parses with the built-in registry too, so the canvas works offline', () => {
    // Every operator Alpha158 uses must be in the fallback as well, or opening
    // an indicator with the API down would fail on an operator that exists.
    for (const { name, expression } of INDICATORS) {
      expect(() => read(expression, FALLBACK_REGISTRY), name).not.toThrow()
    }
  })

  it('names only fields the expression actually reads', () => {
    for (const { name, expression, fields } of INDICATORS) {
      const found = [...expression.matchAll(/\$([A-Za-z_]\w*)/g)].map((m) => m[1])
      expect(new Set(fields), name).toEqual(new Set(found))
    }
  })

  it('files MIN under the rolling LOW group, not the price family', () => {
    // The one case that makes generating per family rather than parsing names
    // load-bearing: the `LOW` rolling key emits MIN5..MIN60.
    const min5 = INDICATORS.find((i) => i.name === 'MIN5')!
    expect(min5.family).toBe('rolling')
    expect(min5.group).toBe('LOW')
    const low0 = INDICATORS.find((i) => i.name === 'LOW0')!
    expect(low0.family).toBe('price')
  })

  it('marks the 158 the handler actually trains on', () => {
    // The TS side gets its own pin so the field cannot rot in the fixture
    // unnoticed. 184 is the vocabulary; 158 is what reaches a model.
    const trained = INDICATORS.filter((i) => i.in_handler)
    expect(trained).toHaveLength(158)

    // Every candle feature and every rolling indicator, but only four price
    // lags and no volume lag at all -- the least guessable part of the split.
    expect(trained.filter((i) => i.family === 'kbar')).toHaveLength(9)
    expect(trained.filter((i) => i.family === 'rolling')).toHaveLength(145)
    expect(trained.filter((i) => i.family === 'volume')).toHaveLength(0)
    expect(trained.filter((i) => i.family === 'price').map((i) => i.name).sort())
      .toEqual(['HIGH0', 'LOW0', 'OPEN0', 'VWAP0'])
  })

  it('does not mark the two constant indicators as trained on', () => {
    // `$close/$close` and `$volume/($volume+1e-12)`. Both are outside the
    // handler's config, which is presumably why it omits those families.
    for (const name of ['CLOSE0', 'VOLUME0']) {
      expect(INDICATORS.find((i) => i.name === name)!.in_handler, name).toBe(false)
    }
  })

  it('carries a window for everything except the candle features', () => {
    for (const indicator of INDICATORS) {
      if (indicator.family === 'kbar') expect(indicator.window).toBeNull()
      else expect(indicator.window).not.toBeNull()
    }
  })
})
