-- Outlook PDF reports generated by scheduled tasks.
--
-- The scheduler produces an Aion-branded PDF for a day/week/month horizon,
-- uploads it to Supabase Storage, and records the metadata here so the UI can
-- list, preview and download it under the user's own RLS.

-- ---------------------------------------------------------------------------
-- Report metadata
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS aion.outlook_reports (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scheduled_task_id TEXT REFERENCES aion.scheduled_tasks(id) ON DELETE SET NULL,
    user_id           UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    org_id            UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    scope             TEXT NOT NULL CHECK (scope IN ('day', 'week', 'month')),
    anchor_date       TEXT NOT NULL,
    summary           TEXT,
    storage_path      TEXT NOT NULL,
    file_size         INTEGER,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_aion_outlook_reports_owner
    ON aion.outlook_reports(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_aion_outlook_reports_task
    ON aion.outlook_reports(scheduled_task_id);

ALTER TABLE aion.outlook_reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS outlook_reports_select ON aion.outlook_reports;
CREATE POLICY outlook_reports_select ON aion.outlook_reports FOR SELECT
    USING (user_id = (SELECT auth.uid()));

DROP POLICY IF EXISTS outlook_reports_service ON aion.outlook_reports;
CREATE POLICY outlook_reports_service ON aion.outlook_reports FOR ALL
    USING (role() = 'service_role')
    WITH CHECK (role() = 'service_role');

GRANT SELECT ON aion.outlook_reports TO authenticated;
GRANT ALL ON aion.outlook_reports TO service_role;

-- ---------------------------------------------------------------------------
-- Storage bucket for the PDFs
-- ---------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('outlook-reports', 'outlook-reports', false, 52428800)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS outlook_reports_storage_user_select ON storage.objects;
CREATE POLICY outlook_reports_storage_user_select ON storage.objects FOR SELECT
    USING (
        bucket_id = 'outlook-reports'
        AND (storage.foldername(name))[1] = (SELECT auth.uid())::text
    );

DROP POLICY IF EXISTS outlook_reports_storage_service ON storage.objects;
CREATE POLICY outlook_reports_storage_service ON storage.objects FOR ALL
    USING (
        bucket_id = 'outlook-reports'
        AND role() = 'service_role'
    )
    WITH CHECK (
        bucket_id = 'outlook-reports'
        AND role() = 'service_role'
    );

-- ---------------------------------------------------------------------------
-- Allow the new scheduled-task kind
-- ---------------------------------------------------------------------------
ALTER TABLE aion.scheduled_tasks
    DROP CONSTRAINT IF EXISTS scheduled_tasks_kind_check;

ALTER TABLE aion.scheduled_tasks
    ADD CONSTRAINT scheduled_tasks_kind_check
    CHECK (kind IN ('macro_refresh', 'data_refresh', 'run_strategy', 'outlook_report'));
