/**
 * The debounced server preview: spec in, the server's whole answer out.
 *
 * Keeps the YAML view honest — it is regenerated by the backend from the same
 * function that produces the config qrun actually runs, never a client-side
 * approximation. The hook lives above the builder's pane switch on purpose:
 * the pane changes what is rendered, never where state lives, so the preview
 * is identical in both panes and cannot drift in one of them.
 *
 * Race-guarded with a sequence number (the `reqId` idiom `UniversePicker`
 * uses): the debounce cancels the *timer*, never the in-flight request, so
 * without the guard a slow answer for an older spec lands after a fast answer
 * for the current one and poisons the YAML, defects and options together.
 */
import { useCallback, useEffect, useRef, useState } from 'react'

import {
  api,
  type FieldOptions, type SpecDefect, type StrategyCoverage, type StrategyExplain,
  type StrategySpec,
} from '@/lib/api'

export interface StrategyPreviewState {
  /** The backend's own render of the file qrun is handed. */
  yaml: string
  warnings: string[]
  /**
   * The typed half of the same answer.
   *
   * `undefined` means the server did not send any — an older build — and the
   * page falls back to inferring severity and placement from `warnings`. An
   * empty array is a real answer and must not be confused with that.
   */
  defects: SpecDefect[] | undefined
  /** What each field may be set to, judged against the rest of the spec. */
  options: Record<string, FieldOptions> | undefined
  /** Advisory store facts from the same preview call. Never a blocker. */
  coverage: StrategyCoverage | undefined
  /** The prediction target and the store's real date range, from the same call. */
  explain: StrategyExplain | undefined
  /**
   * Preview failures live apart from action failures. The preview refires
   * 300ms after every edit, so letting its success path clear the page's
   * `error` erased a save or run failure moments after it appeared.
   */
  error: string | null
}

export function useStrategyPreview(spec: StrategySpec): StrategyPreviewState {
  const [yaml, setYaml] = useState('')
  const [warnings, setWarnings] = useState<string[]>([])
  const [defects, setDefects] = useState<SpecDefect[] | undefined>()
  const [options, setOptions] = useState<Record<string, FieldOptions> | undefined>()
  const [coverage, setCoverage] = useState<StrategyCoverage | undefined>()
  const [explain, setExplain] = useState<StrategyExplain | undefined>()
  const [error, setError] = useState<string | null>(null)

  const previewSeq = useRef(0)
  const preview = useCallback(async () => {
    const seq = ++previewSeq.current
    try {
      const r = await api.previewStrategy(spec)
      if (seq !== previewSeq.current) return
      setYaml(r.yaml)
      setWarnings(r.warnings)
      setDefects(r.defects)
      setOptions(r.options)
      setCoverage(r.coverage)
      setExplain(r.explain)
      setError(null)
    } catch (e) {
      if (seq !== previewSeq.current) return
      setError(e instanceof Error ? e.message : 'Preview failed')
    }
  }, [spec])

  useEffect(() => {
    const t = setTimeout(() => void preview(), 300)
    return () => clearTimeout(t)
  }, [preview])

  return { yaml, warnings, defects, options, coverage, explain, error }
}
