"""Write the registry and library out as fixtures the UI test suite reads.

    python -m webapp.api.factorlab.export

The vitest suite needs the real 184 expressions to prove the parser handles
them, but it cannot import qlib. Committing generated JSON is the seam: a test
asserts the committed file still matches what this writes, and fails with the
command to re-run. That is what makes the fixture a *pin* rather than a copy
that quietly rots -- which is what happened to the hand-transcribed catalog in
factorExpr.test.ts it replaces.

The fixtures are store-independent on purpose. `runnable` depends on which
columns a machine has built, and a fixture that changed after an ingest would
fail the drift test for a reason that has nothing to do with the code.
"""
from __future__ import annotations

import json
from pathlib import Path

from .curated import all_factors, back_days, fields_of, load_families
from .indicators import build_library
from .operators import registry_payload

# .../webapp/api/factorlab/export.py -> .../webapp/ui/src/fixtures
FIXTURES = Path(__file__).resolve().parents[2] / "ui" / "src" / "fixtures"

LIBRARY_JSON = FIXTURES / "library.json"
REGISTRY_JSON = FIXTURES / "registry.json"
CURATED_JSON = FIXTURES / "curated.json"

_HEADER = "Generated by `python -m webapp.api.factorlab.export`. Do not edit."


def library_fixture() -> dict:
    return {
        "_": _HEADER,
        "indicators": [
            {
                "name": i.name,
                "expression": i.expression,
                "family": i.family,
                "group": i.group,
                "window": i.window,
                "fields": i.fields,
                "in_handler": i.in_handler,
            }
            for i in build_library()
        ],
    }


def curated_fixture() -> dict:
    """The curated library, without the store-dependent flags.

    `runnable` and `note` are deliberately absent for the same reason the
    indicator fixture omits them: they depend on which columns a machine has
    built, and a fixture that changed after an ingest would fail the drift test
    for a reason that has nothing to do with the code.
    """
    return {
        "_": _HEADER,
        "families": [
            {"key": f.family, "label": f.label, "count": len(f.factors)}
            for f in load_families()
        ],
        "factors": [
            {
                "name": factor.name,
                "expression": factor.expression,
                "family": family.family,
                "window": factor.window,
                "tags": factor.tags,
                "fields": fields_of(factor.expression),
                "back_days": back_days(factor.expression),
            }
            for family, factor in all_factors()
        ],
    }


def registry_fixture() -> dict:
    return {"_": _HEADER, **registry_payload()}


def render(payload: dict) -> str:
    return json.dumps(payload, indent=2, sort_keys=False) + "\n"


def write() -> list[Path]:
    FIXTURES.mkdir(parents=True, exist_ok=True)
    written = []
    for path, payload in ((LIBRARY_JSON, library_fixture()),
                          (REGISTRY_JSON, registry_fixture()),
                          (CURATED_JSON, curated_fixture())):
        path.write_text(render(payload))
        written.append(path)
    return written


if __name__ == "__main__":
    for path in write():
        print(f"wrote {path}")
